/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IJTI0pp59Mc
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Blog() {
  return (
  <main className="container mx-auto px-4">
        <h1 className="text-6xl font-bold my-12">Latest updates</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <Card className="bg-white text-black">
            <img
              alt="Update image"
              className="w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h2 className="text-xl font-bold">Disrupting malicious uses of AI by state-affiliated threat actors</h2>
              <p className="text-gray-600">Feb 14, 2024</p>
            </CardContent>
          </Card>
          <Card className="bg-white text-black">
            <img
              alt="Update image"
              className="w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h2 className="text-xl font-bold">Memory and new controls for ChatGPT</h2>
              <p className="text-gray-600">Feb 13, 2024</p>
            </CardContent>
          </Card>
          <Card className="bg-white text-black">
            <img
              alt="Update image"
              className="w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h2 className="text-xl font-bold">New embedding models and API updates</h2>
              <p className="text-gray-600">Jan 25, 2024</p>
            </CardContent>
          </Card>
          <Card className="bg-white text-black">
            <img
              alt="Update image"
              className="w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width="300"
            />
            <CardContent>
              <h2 className="text-xl font-bold">
                Democratic inputs to AI grant program: lessons learned and implementation plans
              </h2>
              <p className="text-gray-600">Jan 16, 2024</p>
            </CardContent>
          </Card>
        </div>
        <div className="flex justify-end mt-8">
          <Button className="bg-[#bd1e59] text-white">View all updates</Button>
        </div>
      </main>
   
  )
}
